<a href="https://colab.research.google.com/github/Robertotheto/Algebra_Linear/blob/master/Algebra_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lista de Exercicios**

In [ ]:
import numpy as np

**Calcular a inversa da matriz:**

a)
*   3 7
*   2 5


In [ ]:
matriz = np.array([
    [3,7],
    [2,5],
    ])
matriz_inversa = np.linalg.inv(matriz)
print(matriz_inversa)

[[ 5. -7.]
 [-2.  3.]]


b)
*   2 6
*   4 8

In [ ]:
matriz = np.array([
    [2,6],
    [4,8],
    ])
matriz_inversa = np.linalg.inv(matriz)
print(matriz_inversa)

[[-1.    0.75]
 [ 0.5  -0.25]]


c)
*   3 11
*   2 7


In [ ]:
matriz = np.array([
    [3,11],
    [2,7],
    ])
matriz_inversa = np.linalg.inv(matriz)
print(matriz_inversa)

[[-7. 11.]
 [ 2. -3.]]


d)
*    1  2  0
*    2  1  1
*   -1  0  0

In [ ]:
matriz = np.array([
    [1,2,0],
    [2,1,1],
    [-1,0,0]
    ])
matriz_inversa = np.linalg.inv(matriz)
print(matriz_inversa)

[[ 0.   0.  -1. ]
 [ 0.5  0.   0.5]
 [-0.5  1.   1.5]]


e)
*    2  1  1
*    4 -6  0
*   -2  7  2


In [ ]:
matriz = np.array([
    [2,1,1],
    [4,-6,0],
    [-2,7,2]
    ])
matriz_inversa = np.linalg.inv(matriz)
print(matriz_inversa)

[[ 0.75   -0.3125 -0.375 ]
 [ 0.5    -0.375  -0.25  ]
 [-1.      1.      1.    ]]


f)
*   1 1 -1
*   2 1  1
*   3 -1 1



In [ ]:
matriz = np.array([
    [1,1,-1],
    [2,1,1],
    [3,-1,1]
    ])
matriz_inversa = np.linalg.inv(matriz)
print(matriz_inversa)

[[ 0.25   0.     0.25 ]
 [ 0.125  0.5   -0.375]
 [-0.625  0.5   -0.125]]


**Resolver os seguintes sistemas:**

a)
* 4x−y−3z=15
* 3x−2y+5z=−7
* 2x+3y+4z=7

  
  



In [ ]:
A = np.array([[4, -1, -3],
              [3, -2, 5],
              [2, 3, 4]])
B = np.array([[15],
              [-7],
              [7]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[ 3.]
 [ 3.]
 [-2.]]


b)
* 2x+3y−2z=2
* 3x−5y+4z=5
* x-2y-7z=-24

In [ ]:
A = np.array([[2, 3, -2],
              [3, -5, 4],
              [1, -2, -7]])
B = np.array([[2],
              [5],
              [-24]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]
 [3.]]


c)
* 5x-3y−7z=-5
* 4x−y-z=2
* -2x+4y+8z=10

In [ ]:
A = np.array([[5, -3, -7],
              [4, -1, -1],
              [-2, 4, 8]])
B = np.array([[-5],
              [2],
              [10]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[1.]
 [1.]
 [1.]]


d)
* 6x+2y+4z=0
* -9x−3y-6z=0

In [ ]:
A = np.array([[6,2,4],
              [-9,-3,-6]])
B = np.array([[0],
              [0]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

Resposta x=y=z = 0

e)
* x+4y+6z=11
* 2x+3y+4z=9
* 3x+2y+2z=7

In [ ]:
A = np.array([[1,4,6],
              [2,3,4],
              [3,2,2]])
B = np.array([[11],
              [9],
              [7]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

Resposta não há solução para matriz inversa

f)
* 2x+3y+4z=53
* 3x+5y-4z=2
* 4x+7y-2z=31

In [ ]:
A = np.array([[2,3,4],
              [3,5,-4],
              [4,7,-2]])
B = np.array([[53],
              [2],
              [31]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[3.]
 [5.]
 [8.]]


**Resolvendo o sistema pela regra de cramer**

In [ ]:
a11 = 8
a12 = 5
b11 = 7
b12 = -5
a = 63
b = 27

det_A = (a11 * b12) - (b11 * a12)
det_X = (a * b12) - (a12 * b)
det_Y = (a11 * b) - (a * b11)
x = det_X/det_A
y = det_Y/det_A
print("Solução:")
print("x =", x)
print("y =", y)

Solução:
x = 6.0
y = 3.0


In [ ]:
a11 = 9
a12 = -2
b11 = 7
b12 = 6
a = 31
b = 77

det_A = (a11 * b12) - (b11 * a12)
det_X = (a * b12) - (a12 * b)
det_Y = (a11 * b) - (a * b11)
x = det_X/det_A
y = det_Y/det_A
print("Solução:")
print("x =", x)
print("y =", y)

Solução:
x = 5.0
y = 7.0


In [ ]:
a11 = 21
a12 = -11
b11 = 7
b12 = 5
a = 52
b = 26

det_A = (a11 * b12) - (b11 * a12)
det_X = (a * b12) - (a12 * b)
det_Y = (a11 * b) - (a * b11)
x = det_X/det_A
y = det_Y/det_A
print("Solução:")
print("x =", x)
print("y =", y)

Solução:
x = 3.0
y = 1.0
